In [1]:
# DataCamp:Introduction to Python practice code for learning Jupyter Lab

# Chapter 2 - Python Lists

# Practicing indexing here... 
# Remember that neg values start at LAST of list and work backward.
# And...that list element "counting" starts at zero
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]
print("second element of areas list = " + str(areas[1]))
print("last element of areas list = " + str(areas[-1]))
print("the area of the living room is " + str(areas[-5]))

second element of areas list = 11.25
last element of areas list = 9.5
the area of the living room is 20.0


In [2]:
# Calculations examples...
eat_sleep_area = areas[3] + areas[-3]
print("the area of kitchen plus bedroom is " + str(eat_sleep_area))

the area of kitchen plus bedroom is 28.75


In [3]:
# Slicing and dicing examples...
# Remember: the start index will be included, while the end index is not
downstairs = areas[0:6]
upstairs = areas[6:]
print("the downstairs rooms are " + str(downstairs))
print("the upstairs rooms are " + str(upstairs))

# And some alternative ways to slice, for the same output...
downstairs_alt = areas[:6]
upstairs_alt = areas[6:]
print("the downstairs rooms are " + str(downstairs_alt))
print("the upstairs rooms are " + str(upstairs_alt))

the downstairs rooms are ['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0]
the upstairs rooms are ['bedroom', 10.75, 'bathroom', 9.5]
the downstairs rooms are ['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0]
the upstairs rooms are ['bedroom', 10.75, 'bathroom', 9.5]


In [4]:
# Subsetting lists of lists...
# Remember: first square brackets = sublist selection, 2nd bracket = element within the sublist
house = [['hallway', 11.25], ['kitchen', 18.0], ['living room', 20.0], ['bedroom', 10.75], ['bathroom', 9.5]]
house[-1][1]

9.5

In [5]:
# List manipulation - updating, adding, deleting elements, and assigning to a new list

# Updating examples...
areas[-1] = 10.50
print(areas[8:])
areas[4] = "chill zone"
print(areas[4:6])

# Adding elements...
# Remember: plus sign with lists means "add to the list"
# KEY: 1) index the initial list OR 2) formally list() the initial list variable when
#      assigning the contents to a new variable name! This ensures that the new variable
#      is a SEPARATE LIST, versus a POINTER to the initial list's values!!
areas_1 = areas[:] + ["poolhouse", 24.5]
areas_2 = list(areas_1) + ["garage", 15.45]

# NOTE: you can stack multiple commands back-to-back using the semicolon ;
# Example: command1; command2

# Deleting elements...removing the poolhouse data
print(areas_2)
del(areas_2[-4:-2])
print(areas_2)

['bathroom', 10.5]
['chill zone', 20.0]
['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5, 'poolhouse', 24.5, 'garage', 15.45]
['hallway', 11.25, 'kitchen', 18.0, 'chill zone', 20.0, 'bedroom', 10.75, 'bathroom', 10.5, 'garage', 15.45]


In [6]:
# Functions - some built-in functions
# List: max(), round(), help(round) = argument info on round function
# NOTE: this section is NOT about defining your own functions, but using existing ones

# Examples...print(), type(), len(), str(), int(), bool(), float()
# print() -> pushes output to display within the console
# type() -> display variable type information
# len() -> gives the length of a list variable
# str(), int(), bool(), float() -> convert variables to string, integer, boolean, or float type

var1 = [1, 2, 3, 4]
var2 = True
out2 = int(var2)

print("var1 = " + str(var1))
print("var2 = " + str(var2))
print("Variable var1 is type: " + str(type(var1)) + " and has length: " + str(len(var1)))
print("")
print("While variable out2 is now type: " + str(type(out2)) + " and has value: " + str(out2))

# Example...help()
# Help can be called as: help(command) OR ?command
help(sorted)

# Combine functions to merge two lists and sort the result...
first = [11.25, 18.0, 20.0]
second = [10.75, 9.50]
full = first[:] + second[:]
full_sorted = sorted(full, reverse = True)
print("first = " + str(first))
print("second = " + str(second))
print("merged and sorted full list = " + str(full_sorted))


var1 = [1, 2, 3, 4]
var2 = True
Variable var1 is type: <class 'list'> and has length: 4

While variable out2 is now type: <class 'int'> and has value: 1
Help on built-in function sorted in module builtins:

sorted(iterable, /, *, key=None, reverse=False)
    Return a new list containing all items from the iterable in ascending order.
    
    A custom key function can be supplied to customize the sort order, and the
    reverse flag can be set to request the result in descending order.

first = [11.25, 18.0, 20.0]
second = [10.75, 9.5]
merged and sorted full list = [20.0, 18.0, 11.25, 10.75, 9.5]


In [7]:
# Methods - functions that belong to *OBJECTS*

# SIDE NOTE - TWO WAYS to get a list of all the methods belonging to an object

# FIRST WAY: type help() on the object; for example: help(list)
# Note - methods beginning with "__" are called dunder methods.
# We typically don't want the dunder methods. The second way, below, shows how to list out
# methods while excluding any dunder methods.

# SECOND WAY:
# Use the code below, replacing "list" with the object name you want info on
method_list = []

for attribute in dir(list):
    # Get the attribute value
    attribute_value = getattr(list, attribute)
    # Check that it is callable, meaning available to code with
    if callable(attribute_value):
        # Filter all dunder (__ prefix) methods
        if attribute.startswith('__') == False:
            method_list.append(attribute)
            
print("Methods for the list object: ")
print(method_list)

# Back to DataCamp course...
# Methods are specific to the object.
# Objects may have the same method name, but the method's behavior is specific to the object.
# Example...
sister = "lizzie" # string object
height = 1.73  # float object
fam = ["liz", 1.73, "emma", 1.68, "mom", 1.71, "dad", 1.89] # list object

print(sister.index("z")) # returns the 1st character position of z in the string
print(fam.index("mom"))  # returns the element position of "mom" in the list

# KEY: some methods can change the object that they are assigned to.
# For example: the append method (which can only append one item)
fam.append("todd")
fam.append(1.75)
print(fam)

# Examples...
sister_up = sister.upper()
print(sister_up)

Methods for the list object: 
['append', 'clear', 'copy', 'count', 'extend', 'index', 'insert', 'pop', 'remove', 'reverse', 'sort']
2
4
['liz', 1.73, 'emma', 1.68, 'mom', 1.71, 'dad', 1.89, 'todd', 1.75]
LIZZIE


In [8]:
# Packages - installing, importing, and then using packages

# SIDE NOTE - how to list installed packages
# 1) within console - use help("modules")
# 2) terminal window - use A) pip list, or B) pip freeze

# Note: ran help("modules") to confirm that math package is already installed
# Module math.pi provides the value of pi for calculations
# Use ** to declare an exponent. Example: r squared is "r ** 2"

import math
r = 0.43
C = 2 * math.pi * r
A = math.pi * r ** 2
print("Circumference: " + str(C))
print("Area: " + str(A))
print("")

# To import a specific function from a package: "from package import function"
# Example - from math import radians
# If importing just a specific funtion, you DON'T need to use the dot notation.
# Example (replace below code with): dist = r_moon * radians(12)

r_moon = 192500
dist = r_moon * math.radians(12)
print("Travel distance of moon over 12 degrees: " + str(dist) + " miles")

help("modules")

Circumference: 2.701769682087222
Area: 0.5808804816487527

Travel distance of moon over 12 degrees: 40317.10572106901 miles

Please wait a moment while I gather a list of all available modules...



/Users/toddalbin/miniforge3/lib/python3.9/site-packages/IPython/kernel/__init__.py:12: ShimWarning: The `IPython.kernel` package has been deprecated since IPython 4.0.You should import from ipykernel or jupyter_client instead.
  warn("The `IPython.kernel` package has been deprecated since IPython 4.0."


IPython             argparse            importlib_metadata  rmagic
OpenSSL             array               inspect             ruamel_yaml
__future__          ast                 io                  runpy
_abc                async_generator     ipaddress           sched
_aix_support        asynchat            ipykernel           secrets
_ast                asyncio             ipykernel_launcher  select
_asyncio            asyncore            ipython_genutils    selectors
_bisect             atexit              itertools           send2trash
_blake2             attr                jedi                setuptools
_bootlocale         audioop             jinja2              shelve
_bootsubprocess     autoreload          json                shlex
_bz2                babel               json5               shutil
_cffi_backend       backcall            jsonschema          signal
_codecs             backports           jupyter             site
_codecs_cn          base64              jupyter_cl

/Users/toddalbin/miniforge3/lib/python3.9/pkgutil.py:108: VisibleDeprecationWarning: zmq.eventloop.minitornado is deprecated in pyzmq 14.0 and will be removed.
    Install tornado itself to use zmq with the tornado IOLoop.
    
  yield from walk_packages(path, info.name+'.', onerror)


In [9]:
# Need to install Numpy package for continued work within Datacamp

# IMPORTANT
# Here is how to install a package within a Jupyter Lab Python Notebook
# Note: this method is specific to how ipython was loaded for this Jupyter Lab,
# using the miniforge download (which is a conda install) - date: 7/30/2021

import sys
sys.executable
!conda install --yes --prefix {sys.prefix} numpy

Solving environment: done

# All requested packages already installed.



In [10]:
# Let's verify that the package loaded and shows within Jupyter Lab...
help("modules")
# SUCCESS!


Please wait a moment while I gather a list of all available modules...

IPython             argparse            importlib_metadata  rmagic
OpenSSL             array               inspect             ruamel_yaml
__future__          ast                 io                  runpy
_abc                async_generator     ipaddress           sched
_aix_support        asynchat            ipykernel           secrets
_ast                asyncio             ipykernel_launcher  select
_asyncio            asyncore            ipython_genutils    selectors
_bisect             atexit              itertools           send2trash
_blake2             attr                jedi                setuptools
_bootlocale         audioop             jinja2              shelve
_bootsubprocess     autoreload          json                shlex
_bz2                babel               json5               shutil
_cffi_backend       backcall            jsonschema          signal
_codecs             backports           ju

In [11]:
# Numpy - arrays, array subsetting, 2D arrays, 2D array arithmetic, numpy statistics

# Creating arrays...use numpy.array() function
baseball = [180, 215, 210, 210, 188, 176, 209, 200]
import numpy as np
np_baseball = np.array(baseball)
print("np_baseball: " + str(np_baseball))
print(type(np_baseball))


np_baseball: [180 215 210 210 188 176 209 200]
<class 'numpy.ndarray'>


In [12]:
# Want to install pandas package. This provides a way to import csv data.
# Will use to create a numpy array of baseball data from baseball.csv file.

!conda install --yes --prefix {sys.prefix} pandas

# Verify the install...
help("modules")
# Success!

Solving environment: done

## Package Plan ##

  environment location: /Users/toddalbin/miniforge3

  added / updated specs:
    - pandas


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    pandas-1.3.1               |   py39h4d6be9b_0        11.7 MB  conda-forge
    ------------------------------------------------------------
                                           Total:        11.7 MB

The following NEW packages will be INSTALLED:

  pandas             conda-forge/osx-64::pandas-1.3.1-py39h4d6be9b_0



pandas-1.3.1         | 11.7 MB   | ##################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

Please wait a moment while I gather a list of all available modules...

IPython             argparse            importlib_metadata  rlcompleter
OpenSSL             array               inspect             rmagic
__future__ 

In [34]:
# Import baseball.csv file, which creates a dataframe, then inspect
import pandas as pd
baseball_data = pd.read_csv('baseball.csv')
baseball_data.head() # use to read the first 5 lines of the table
baseball_data.info() # get basic info on the dataframe3

# Slice out just the height data
height = baseball_data['Height'].to_numpy()
print(height[:10])

# Slice out the weight data
weight = baseball_data['Weight'].to_numpy()
print(weight[:10])

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1015 entries, 0 to 1014
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Name         1015 non-null   object 
 1   Team         1015 non-null   object 
 2   Position     1015 non-null   object 
 3   Height       1015 non-null   int64  
 4   Weight       1015 non-null   int64  
 5   Age          1015 non-null   float64
 6   PosCategory  1015 non-null   object 
dtypes: float64(1), int64(2), object(4)
memory usage: 55.6+ KB
[74 74 72 72 73 69 69 71 76 71]
[180 215 210 210 188 176 209 200 231 180]


In [35]:
# Back to Datacamp course...

# Use numpy to calculate bmi values
np_height_m = np.array(height) * 0.0254
np_weight_kg = np.array(weight) * 0.453592
bmi = np_weight_kg / (np_height_m ** 2)
print(bmi[:10])

[23.11037639 27.60406069 28.48080465 28.48080465 24.80333518 25.99036864
 30.86356276 27.89402921 28.11789135 25.10462629]


In [37]:
# Can use boolean numpy array to subset the created bmi table...
# Let's identify the bmi's that are < 21
light = bmi < 21
print(light)
print(bmi[light])

[False False False ... False False False]
[20.54255679 20.54255679 20.69282047 20.69282047 20.34343189 20.34343189
 20.69282047 20.15883472 19.4984471  20.69282047 20.9205219 ]


In [47]:
# 2D Numpy Arrays - creating, subsetting, element-wise calculations

# Recast baseball as a list of lists...and convert to numpy array...
baseball = [[180, 78.4], [215, 102.7], [210, 98.5], [188, 75.2]]
np_baseball = np.array(baseball)
print("The array type info: " + str(type(np_baseball)))
print("Shape of our array: " + str(np_baseball.shape))
print("Here is the array call output:")
np_baseball

The array type info: <class 'numpy.ndarray'>
Shape of our array: (4, 2)
Here is the array call output:


array([[180. ,  78.4],
       [215. , 102.7],
       [210. ,  98.5],
       [188. ,  75.2]])

In [59]:
# Recast baseball as a 2D array with both height and weight data from full csv file...
# This requires a new structure for the originial data - each player's 
# heigh and weight as a list of lists.

# Capture just the columns Height and Weight from the dataframe, convert to list
htwt_baseball = baseball_data[['Height', 'Weight']]
print(htwt_baseball)                       # verify just the two columns
print(type(htwt_baseball))                 # new object is a dataframe
htwt_lol = htwt_baseball.values.tolist()   # push full df out as list of lists
print(htwt_lol)                            # verify proper format
print(type(htwt_lol))                      # verify type 

# Capture columns Height, Weight, and Age, convert to list, convert to numpy array
hwa_baseball = baseball_data[['Height', 'Weight', 'Age']]
hwa_lol = hwa_baseball.values.tolist()
np_hwa_baseball = np.array(hwa_lol)

      Height  Weight
0         74     180
1         74     215
2         72     210
3         72     210
4         73     188
...      ...     ...
1010      73     190
1011      74     180
1012      75     205
1013      75     190
1014      73     195

[1015 rows x 2 columns]
<class 'pandas.core.frame.DataFrame'>
[[74, 180], [74, 215], [72, 210], [72, 210], [73, 188], [69, 176], [69, 209], [71, 200], [76, 231], [71, 180], [73, 188], [73, 180], [74, 185], [74, 160], [69, 180], [70, 185], [73, 189], [75, 185], [78, 219], [79, 230], [76, 205], [74, 230], [76, 195], [72, 180], [71, 192], [75, 225], [77, 203], [74, 195], [73, 182], [74, 188], [78, 200], [73, 180], [75, 200], [73, 200], [75, 245], [75, 240], [74, 215], [69, 185], [71, 175], [74, 199], [73, 200], [73, 215], [76, 200], [74, 205], [74, 206], [70, 186], [72, 188], [77, 220], [74, 210], [70, 195], [73, 200], [75, 200], [76, 212], [76, 224], [78, 210], [74, 205], [74, 220], [76, 195], [77, 200], [81, 260], [78, 228], [75, 270], [7

In [56]:
# Back to Datacamp - we'll use htwt_lol as our base data to make the 2D numpy array
np_baseball = np.array(htwt_lol)
print(np_baseball)
print(type(np_baseball))

# Selecting examples...
print(np_baseball[49,:])          # print out the 50th row
np_weight_lb = np_baseball[:, 1]  # create numpy array of just the 2nd column, weight
print(type(np_weight_lb))         # confirm this as a numpy array
print(np_baseball[123, 0])        # print out height of 124th player

[[ 74 180]
 [ 74 215]
 [ 72 210]
 ...
 [ 75 205]
 [ 75 190]
 [ 73 195]]
<class 'numpy.ndarray'>
[ 70 195]
<class 'numpy.ndarray'>
75


In [61]:
# 2D Arithmetic
# KEY - doing arithmetic with a ndarray DOESN'T change the original array.
# Using the np_hwa_baseball numpy array now; has 3 columns...
conversion = np.array([0.0254, 0.453592, 1])   # conversion factors to m, kg, (no change)
print(np_hwa_baseball * conversion)            # calculate converted values
print(np_hwa_baseball)                         # NOTICE - no change to np_baseball
np_hwa_metric = np_hwa_baseball * conversion   # have saved our converted values
print(np_hwa_metric)                           # now they are available for future use

[[ 1.8796  81.64656 22.99   ]
 [ 1.8796  97.52228 34.69   ]
 [ 1.8288  95.25432 30.78   ]
 ...
 [ 1.905   92.98636 25.19   ]
 [ 1.905   86.18248 31.01   ]
 [ 1.8542  88.45044 27.92   ]]
[[ 74.   180.    22.99]
 [ 74.   215.    34.69]
 [ 72.   210.    30.78]
 ...
 [ 75.   205.    25.19]
 [ 75.   190.    31.01]
 [ 73.   195.    27.92]]
[[ 1.8796  81.64656 22.99   ]
 [ 1.8796  97.52228 34.69   ]
 [ 1.8288  95.25432 30.78   ]
 ...
 [ 1.905   92.98636 25.19   ]
 [ 1.905   86.18248 31.01   ]
 [ 1.8542  88.45044 27.92   ]]


In [65]:
# Basic Statistics - using built-in numpy functions
# Continue using the np_hwa_baseball array...
print(np.mean(np_hwa_baseball[:,0]))           # calculate the mean height
print(np.median(np_hwa_baseball[:,0]))         # calculate the median height
print(np.std(np_hwa_baseball[:,0]))            # standard deviation of height
print(np.corrcoef(np_hwa_baseball[:,0], np_hwa_baseball[:,1]))  # correlation coefficient

73.6896551724138
74.0
2.312791881046546
[[1.         0.53153932]
 [0.53153932 1.        ]]
